name: leaf-bluefin-neo
description: just my personal bluefin.
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /
        
  - type: script
    scripts:
      - setup_repos.sh
      
  - type: rpm-ostree
    remove:
      - gnome-shell-extension-search-light
      - gnome-shell-extension-logo-menu
      - gnome-classic-session
      - gnome-classic-session-xsession
      - yaru-theme
      - containerd.io
      - docker-ce
      - docker-ce-cli
      - docker-buildx-plugin
      - docker-compose-plugin
      - docker-ce-rootless-extras
    install:
      - gnome-shell-extension-caffeine
      - podman-docker
      - podman-compose
      - duperemove
      - corectrl 
      - qt5-qtbase
      - qt6ct
      - mangohud
      - gamescope
      - gamemode
      - sunshind
      - libvirt-client
      - qemu-kvm
      - libvirt-daemon-kvm
      - libvirt-daemon-config-network
      - virt-install
      - virt-manager
      - edk2-ovmf
      - swtpm
      - virt-top
      - libguestfs-tools
      - tuned
      - bridge-utils
      - android-tools
      - scrcpy
      - waydroid
    
  - type: default-flatpaks
    notify: true 
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (System)"
      install:

      remove:
      
  - type: yafti
    custom-flatpaks:
      - FireFox: org.mozilla.firefox
      - LibreOffice: org.libreoffice.libreoffice
      - ThunderBird: org.mozilla.Thunderbird
    
  - type: script
    scripts:
      - unsetup_repos.sh
      
  - type: signing
